import { z } from "zod";

export type Country = {
  value: string;
  country: string;
  abbreviation: string;
  currency: string;
};

// Readonly Country List Array
export const COUNTRY_CODES: ReadonlyArray<Country> = [
  { value: "+93", country: "Afghanistan", abbreviation: "AF", currency: "AFN" },
  { value: "+355", country: "Albania", abbreviation: "AL", currency: "ALL" },
  { value: "+213", country: "Algeria", abbreviation: "DZ", currency: "DZD" },
  {
    value: "+1-684",
    country: "American Samoa",
    abbreviation: "AS",
    currency: "USD",
  },
  { value: "+376", country: "Andorra", abbreviation: "AD", currency: "EUR" },
  { value: "+244", country: "Angola", abbreviation: "AO", currency: "AOA" },
  { value: "+1-264", country: "Anguilla", abbreviation: "AI", currency: "XCD" },
  {
    value: "+672",
    country: "Antarctica",
    abbreviation: "AQ",
    currency: "N/A",
  },
  {
    value: "+1-268",
    country: "Antigua and Barbuda",
    abbreviation: "AG",
    currency: "XCD",
  },
  { value: "+54", country: "Argentina", abbreviation: "AR", currency: "ARS" },
  { value: "+374", country: "Armenia", abbreviation: "AM", currency: "AMD" },
  { value: "+297", country: "Aruba", abbreviation: "AW", currency: "AWG" },
  { value: "+61", country: "Australia", abbreviation: "AU", currency: "AUD" },
  { value: "+43", country: "Austria", abbreviation: "AT", currency: "EUR" },
  { value: "+994", country: "Azerbaijan", abbreviation: "AZ", currency: "AZN" },
  { value: "+1-242", country: "Bahamas", abbreviation: "BS", currency: "BSD" },
  { value: "+973", country: "Bahrain", abbreviation: "BH", currency: "BHD" },
  { value: "+880", country: "Bangladesh", abbreviation: "BD", currency: "BDT" },
  { value: "+1-246", country: "Barbados", abbreviation: "BB", currency: "BBD" },
  { value: "+375", country: "Belarus", abbreviation: "BY", currency: "BYN" },
  { value: "+32", country: "Belgium", abbreviation: "BE", currency: "EUR" },
  { value: "+501", country: "Belize", abbreviation: "BZ", currency: "BZD" },
  { value: "+229", country: "Benin", abbreviation: "BJ", currency: "XOF" },
  { value: "+1-441", country: "Bermuda", abbreviation: "BM", currency: "BMD" },
  { value: "+975", country: "Bhutan", abbreviation: "BT", currency: "BTN" },
  { value: "+591", country: "Bolivia", abbreviation: "BO", currency: "BOB" },
  {
    value: "+387",
    country: "Bosnia and Herzegovina",
    abbreviation: "BA",
    currency: "BAM",
  },
  { value: "+267", country: "Botswana", abbreviation: "BW", currency: "BWP" },
  { value: "+55", country: "Brazil", abbreviation: "BR", currency: "BRL" },
  {
    value: "+246",
    country: "British Indian Ocean Territory",
    abbreviation: "IO",
    currency: "USD",
  },
  {
    value: "+1-284",
    country: "British Virgin Islands",
    abbreviation: "VG",
    currency: "USD",
  },
  { value: "+673", country: "Brunei", abbreviation: "BN", currency: "BND" },
  { value: "+359", country: "Bulgaria", abbreviation: "BG", currency: "BGN" },
  {
    value: "+226",
    country: "Burkina Faso",
    abbreviation: "BF",
    currency: "XOF",
  },
  { value: "+257", country: "Burundi", abbreviation: "BI", currency: "BIF" },
  { value: "+855", country: "Cambodia", abbreviation: "KH", currency: "KHR" },
  { value: "+237", country: "Cameroon", abbreviation: "CM", currency: "XAF" },
  { value: "+1", country: "Canada", abbreviation: "CA", currency: "CAD" },
  { value: "+238", country: "Cape Verde", abbreviation: "CV", currency: "CVE" },
  {
    value: "+1-345",
    country: "Cayman Islands",
    abbreviation: "KY",
    currency: "KYD",
  },
  {
    value: "+236",
    country: "Central African Republic",
    abbreviation: "CF",
    currency: "XAF",
  },
  { value: "+235", country: "Chad", abbreviation: "TD", currency: "XAF" },
  { value: "+56", country: "Chile", abbreviation: "CL", currency: "CLP" },
  { value: "+86", country: "China", abbreviation: "CN", currency: "CNY" },
  { value: "+57", country: "Colombia", abbreviation: "CO", currency: "COP" },
  { value: "+269", country: "Comoros", abbreviation: "KM", currency: "KMF" },
  {
    value: "+682",
    country: "Cook Islands",
    abbreviation: "CK",
    currency: "NZD",
  },
  { value: "+506", country: "Costa Rica", abbreviation: "CR", currency: "CRC" },
  { value: "+385", country: "Croatia", abbreviation: "HR", currency: "HRK" },
  { value: "+53", country: "Cuba", abbreviation: "CU", currency: "CUP" },
  { value: "+599", country: "Curaçao", abbreviation: "CW", currency: "ANG" },
  { value: "+357", country: "Cyprus", abbreviation: "CY", currency: "EUR" },
  {
    value: "+420",
    country: "Czech Republic",
    abbreviation: "CZ",
    currency: "CZK",
  },
  {
    value: "+243",
    country: "Democratic Republic of the Congo",
    abbreviation: "CD",
    currency: "CDF",
  },
  { value: "+45", country: "Denmark", abbreviation: "DK", currency: "DKK" },
  { value: "+253", country: "Djibouti", abbreviation: "DJ", currency: "DJF" },
  { value: "+1-767", country: "Dominica", abbreviation: "DM", currency: "XCD" },
  {
    value: "+1-809",
    country: "Dominican Republic",
    abbreviation: "DO",
    currency: "DOP",
  },
  { value: "+593", country: "Ecuador", abbreviation: "EC", currency: "USD" },
  { value: "+20", country: "Egypt", abbreviation: "EG", currency: "EGP" },
  {
    value: "+503",
    country: "El Salvador",
    abbreviation: "SV",
    currency: "USD",
  },
  {
    value: "+240",
    country: "Equatorial Guinea",
    abbreviation: "GQ",
    currency: "XAF",
  },
  { value: "+291", country: "Eritrea", abbreviation: "ER", currency: "ERN" },
  { value: "+372", country: "Estonia", abbreviation: "EE", currency: "EUR" },
  { value: "+251", country: "Ethiopia", abbreviation: "ET", currency: "ETB" },
  {
    value: "+500",
    country: "Falkland Islands",
    abbreviation: "FK",
    currency: "FKP",
  },
  {
    value: "+298",
    country: "Faroe Islands",
    abbreviation: "FO",
    currency: "DKK",
  },
  { value: "+679", country: "Fiji", abbreviation: "FJ", currency: "FJD" },
  { value: "+358", country: "Finland", abbreviation: "FI", currency: "EUR" },
  { value: "+33", country: "France", abbreviation: "FR", currency: "EUR" },
  { value: "+241", country: "Gabon", abbreviation: "GA", currency: "XAF" },
  { value: "+220", country: "Gambia", abbreviation: "GM", currency: "GMD" },
  { value: "+995", country: "Georgia", abbreviation: "GE", currency: "GEL" },
  { value: "+49", country: "Germany", abbreviation: "DE", currency: "EUR" },
  { value: "+233", country: "Ghana", abbreviation: "GH", currency: "GHS" },
  { value: "+350", country: "Gibraltar", abbreviation: "GI", currency: "GIP" },
  { value: "+30", country: "Greece", abbreviation: "GR", currency: "EUR" },
  { value: "+299", country: "Greenland", abbreviation: "GL", currency: "DKK" },
  { value: "+1-473", country: "Grenada", abbreviation: "GD", currency: "XCD" },
  { value: "+1-671", country: "Guam", abbreviation: "GU", currency: "USD" },
  { value: "+502", country: "Guatemala", abbreviation: "GT", currency: "GTQ" },
  {
    value: "+44-1481",
    country: "Guernsey",
    abbreviation: "GG",
    currency: "GBP",
  },
  { value: "+224", country: "Guinea", abbreviation: "GN", currency: "GNF" },
  {
    value: "+245",
    country: "Guinea-Bissau",
    abbreviation: "GW",
    currency: "XOF",
  },
  { value: "+592", country: "Guyana", abbreviation: "GY", currency: "GYD" },
  { value: "+509", country: "Haiti", abbreviation: "HT", currency: "HTG" },
  { value: "+504", country: "Honduras", abbreviation: "HN", currency: "HNL" },
  { value: "+852", country: "Hong Kong", abbreviation: "HK", currency: "HKD" },
  { value: "+36", country: "Hungary", abbreviation: "HU", currency: "HUF" },
  { value: "+354", country: "Iceland", abbreviation: "IS", currency: "ISK" },
  { value: "+91", country: "India", abbreviation: "IN", currency: "INR" },
  { value: "+62", country: "Indonesia", abbreviation: "ID", currency: "IDR" },
  { value: "+98", country: "Iran", abbreviation: "IR", currency: "IRR" },
  { value: "+964", country: "Iraq", abbreviation: "IQ", currency: "IQD" },
  { value: "+353", country: "Ireland", abbreviation: "IE", currency: "EUR" },
  {
    value: "+44-1624",
    country: "Isle of Man",
    abbreviation: "IM",
    currency: "GBP",
  },
  { value: "+972", country: "Israel", abbreviation: "IL", currency: "ILS" },
  { value: "+39", country: "Italy", abbreviation: "IT", currency: "EUR" },
  {
    value: "+225",
    country: "Ivory Coast",
    abbreviation: "CI",
    currency: "XOF",
  },
  { value: "+1-876", country: "Jamaica", abbreviation: "JM", currency: "JMD" },
  { value: "+81", country: "Japan", abbreviation: "JP", currency: "JPY" },
  { value: "+44-1534", country: "Jersey", abbreviation: "JE", currency: "GBP" },
  { value: "+962", country: "Jordan", abbreviation: "JO", currency: "JOD" },
  { value: "+7", country: "Kazakhstan", abbreviation: "KZ", currency: "KZT" },
  { value: "+254", country: "Kenya", abbreviation: "KE", currency: "KES" },
  { value: "+686", country: "Kiribati", abbreviation: "KI", currency: "AUD" },
  { value: "+383", country: "Kosovo", abbreviation: "XK", currency: "EUR" },
  { value: "+965", country: "Kuwait", abbreviation: "KW", currency: "KWD" },
  { value: "+996", country: "Kyrgyzstan", abbreviation: "KG", currency: "KGS" },
  { value: "+856", country: "Laos", abbreviation: "LA", currency: "LAK" },
  { value: "+371", country: "Latvia", abbreviation: "LV", currency: "EUR" },
  { value: "+961", country: "Lebanon", abbreviation: "LB", currency: "LBP" },
  { value: "+266", country: "Lesotho", abbreviation: "LS", currency: "LSL" },
  { value: "+231", country: "Liberia", abbreviation: "LR", currency: "LRD" },
  { value: "+218", country: "Libya", abbreviation: "LY", currency: "LYD" },
  {
    value: "+423",
    country: "Liechtenstein",
    abbreviation: "LI",
    currency: "CHF",
  },
  { value: "+370", country: "Lithuania", abbreviation: "LT", currency: "EUR" },
  { value: "+352", country: "Luxembourg", abbreviation: "LU", currency: "EUR" },
  { value: "+853", country: "Macau", abbreviation: "MO", currency: "MOP" },
  {
    value: "+389",
    country: "North Macedonia",
    abbreviation: "MK",
    currency: "MKD",
  },
  { value: "+261", country: "Madagascar", abbreviation: "MG", currency: "MGA" },
  { value: "+265", country: "Malawi", abbreviation: "MW", currency: "MWK" },
  { value: "+60", country: "Malaysia", abbreviation: "MY", currency: "MYR" },
  { value: "+960", country: "Maldives", abbreviation: "MV", currency: "MVR" },
  { value: "+223", country: "Mali", abbreviation: "ML", currency: "XOF" },
  { value: "+356", country: "Malta", abbreviation: "MT", currency: "EUR" },
  {
    value: "+692",
    country: "Marshall Islands",
    abbreviation: "MH",
    currency: "USD",
  },
  { value: "+222", country: "Mauritania", abbreviation: "MR", currency: "MRU" },
  { value: "+230", country: "Mauritius", abbreviation: "MU", currency: "MUR" },
  { value: "+262", country: "Réunion", abbreviation: "RE", currency: "EUR" },
  { value: "+52", country: "Mexico", abbreviation: "MX", currency: "MXN" },
  { value: "+691", country: "Micronesia", abbreviation: "FM", currency: "USD" },
  { value: "+373", country: "Moldova", abbreviation: "MD", currency: "MDL" },
  { value: "+377", country: "Monaco", abbreviation: "MC", currency: "EUR" },
  { value: "+976", country: "Mongolia", abbreviation: "MN", currency: "MNT" },
  { value: "+382", country: "Montenegro", abbreviation: "ME", currency: "EUR" },
  {
    value: "+1-664",
    country: "Montserrat",
    abbreviation: "MS",
    currency: "XCD",
  },
  { value: "+212", country: "Morocco", abbreviation: "MA", currency: "MAD" },
  { value: "+258", country: "Mozambique", abbreviation: "MZ", currency: "MZN" },
  { value: "+95", country: "Myanmar", abbreviation: "MM", currency: "MMK" },
  { value: "+264", country: "Namibia", abbreviation: "NA", currency: "NAD" },
  { value: "+674", country: "Nauru", abbreviation: "NR", currency: "AUD" },
  { value: "+977", country: "Nepal", abbreviation: "NP", currency: "NPR" },
  { value: "+31", country: "Netherlands", abbreviation: "NL", currency: "EUR" },
  {
    value: "+687",
    country: "New Caledonia",
    abbreviation: "NC",
    currency: "XPF",
  },
  { value: "+64", country: "New Zealand", abbreviation: "NZ", currency: "NZD" },
  { value: "+505", country: "Nicaragua", abbreviation: "NI", currency: "NIO" },
  { value: "+227", country: "Niger", abbreviation: "NE", currency: "XOF" },
  { value: "+234", country: "Nigeria", abbreviation: "NG", currency: "NGN" },
  { value: "+683", country: "Niue", abbreviation: "NU", currency: "NZD" },
  {
    value: "+850",
    country: "North Korea",
    abbreviation: "KP",
    currency: "KPW",
  },
  {
    value: "+1-670",
    country: "Northern Mariana Islands",
    abbreviation: "MP",
    currency: "USD",
  },
  { value: "+47", country: "Norway", abbreviation: "NO", currency: "NOK" },
  { value: "+968", country: "Oman", abbreviation: "OM", currency: "OMR" },
  { value: "+92", country: "Pakistan", abbreviation: "PK", currency: "PKR" },
  { value: "+680", country: "Palau", abbreviation: "PW", currency: "USD" },
  { value: "+970", country: "Palestine", abbreviation: "PS", currency: "ILS" },
  { value: "+507", country: "Panama", abbreviation: "PA", currency: "PAB" },
  {
    value: "+675",
    country: "Papua New Guinea",
    abbreviation: "PG",
    currency: "PGK",
  },
  { value: "+595", country: "Paraguay", abbreviation: "PY", currency: "PYG" },
  { value: "+51", country: "Peru", abbreviation: "PE", currency: "PEN" },
  { value: "+63", country: "Philippines", abbreviation: "PH", currency: "PHP" },
  { value: "+48", country: "Poland", abbreviation: "PL", currency: "PLN" },
  { value: "+351", country: "Portugal", abbreviation: "PT", currency: "EUR" },
  {
    value: "+1-787",
    country: "Puerto Rico",
    abbreviation: "PR",
    currency: "USD",
  },
  { value: "+974", country: "Qatar", abbreviation: "QA", currency: "QAR" },
  {
    value: "+242",
    country: "Republic of the Congo",
    abbreviation: "CG",
    currency: "XAF",
  },
  { value: "+40", country: "Romania", abbreviation: "RO", currency: "RON" },
  { value: "+7", country: "Russia", abbreviation: "RU", currency: "RUB" },
  { value: "+250", country: "Rwanda", abbreviation: "RW", currency: "RWF" },
  {
    value: "+290",
    country: "Saint Helena",
    abbreviation: "SH",
    currency: "SHP",
  },
  {
    value: "+1-869",
    country: "Saint Kitts and Nevis",
    abbreviation: "KN",
    currency: "XCD",
  },
  {
    value: "+1-758",
    country: "Saint Lucia",
    abbreviation: "LC",
    currency: "XCD",
  },
  {
    value: "+508",
    country: "Saint Pierre and Miquelon",
    abbreviation: "PM",
    currency: "EUR",
  },
  {
    value: "+1-784",
    country: "Saint Vincent and the Grenadines",
    abbreviation: "VC",
    currency: "XCD",
  },
  { value: "+685", country: "Samoa", abbreviation: "WS", currency: "WST" },
  { value: "+378", country: "San Marino", abbreviation: "SM", currency: "EUR" },
  {
    value: "+239",
    country: "Sao Tome and Principe",
    abbreviation: "ST",
    currency: "STN",
  },
  {
    value: "+966",
    country: "Saudi Arabia",
    abbreviation: "SA",
    currency: "SAR",
  },
  { value: "+221", country: "Senegal", abbreviation: "SN", currency: "XOF" },
  { value: "+381", country: "Serbia", abbreviation: "RS", currency: "RSD" },
  { value: "+248", country: "Seychelles", abbreviation: "SC", currency: "SCR" },
  {
    value: "+232",
    country: "Sierra Leone",
    abbreviation: "SL",
    currency: "SLL",
  },
  { value: "+65", country: "Singapore", abbreviation: "SG", currency: "SGD" },
  {
    value: "+1-721",
    country: "Sint Maarten",
    abbreviation: "SX",
    currency: "ANG",
  },
  { value: "+421", country: "Slovakia", abbreviation: "SK", currency: "EUR" },
  { value: "+386", country: "Slovenia", abbreviation: "SI", currency: "EUR" },
  {
    value: "+677",
    country: "Solomon Islands",
    abbreviation: "SB",
    currency: "SBD",
  },
  { value: "+252", country: "Somalia", abbreviation: "SO", currency: "SOS" },
  {
    value: "+27",
    country: "South Africa",
    abbreviation: "ZA",
    currency: "ZAR",
  },
  { value: "+82", country: "South Korea", abbreviation: "KR", currency: "KRW" },
  {
    value: "+211",
    country: "South Sudan",
    abbreviation: "SS",
    currency: "SSP",
  },
  { value: "+34", country: "Spain", abbreviation: "ES", currency: "EUR" },
  { value: "+94", country: "Sri Lanka", abbreviation: "LK", currency: "LKR" },
  { value: "+249", country: "Sudan", abbreviation: "SD", currency: "SDG" },
  { value: "+597", country: "Suriname", abbreviation: "SR", currency: "SRD" },
  {
    value: "+47",
    country: "Svalbard and Jan Mayen",
    abbreviation: "SJ",
    currency: "NOK",
  },
  { value: "+268", country: "Swaziland", abbreviation: "SZ", currency: "SZL" },
  { value: "+46", country: "Sweden", abbreviation: "SE", currency: "SEK" },
  { value: "+41", country: "Switzerland", abbreviation: "CH", currency: "CHF" },
  { value: "+963", country: "Syria", abbreviation: "SY", currency: "SYP" },
  { value: "+886", country: "Taiwan", abbreviation: "TW", currency: "TWD" },
  { value: "+992", country: "Tajikistan", abbreviation: "TJ", currency: "TJS" },
  { value: "+255", country: "Tanzania", abbreviation: "TZ", currency: "TZS" },
  { value: "+66", country: "Thailand", abbreviation: "TH", currency: "THB" },
  { value: "+228", country: "Togo", abbreviation: "TG", currency: "XOF" },
  { value: "+690", country: "Tokelau", abbreviation: "TK", currency: "NZD" },
  { value: "+676", country: "Tonga", abbreviation: "TO", currency: "TOP" },
  {
    value: "+1-868",
    country: "Trinidad and Tobago",
    abbreviation: "TT",
    currency: "TTD",
  },
  { value: "+216", country: "Tunisia", abbreviation: "TN", currency: "TND" },
  { value: "+90", country: "Turkey", abbreviation: "TR", currency: "TRY" },
  {
    value: "+993",
    country: "Turkmenistan",
    abbreviation: "TM",
    currency: "TMT",
  },
  {
    value: "+1-649",
    country: "Turks and Caicos Islands",
    abbreviation: "TC",
    currency: "USD",
  },
  { value: "+688", country: "Tuvalu", abbreviation: "TV", currency: "AUD" },
  {
    value: "+1-340",
    country: "U.S. Virgin Islands",
    abbreviation: "VI",
    currency: "USD",
  },
  { value: "+256", country: "Uganda", abbreviation: "UG", currency: "UGX" },
  { value: "+380", country: "Ukraine", abbreviation: "UA", currency: "UAH" },
  {
    value: "+971",
    country: "United Arab Emirates",
    abbreviation: "AE",
    currency: "AED",
  },
  {
    value: "+44",
    country: "United Kingdom",
    abbreviation: "GB",
    currency: "GBP",
  },
  {
    value: "+1",
    country: "United States",
    abbreviation: "US",
    currency: "USD",
  },
  { value: "+598", country: "Uruguay", abbreviation: "UY", currency: "UYU" },
  { value: "+998", country: "Uzbekistan", abbreviation: "UZ", currency: "UZS" },
  { value: "+678", country: "Vanuatu", abbreviation: "VU", currency: "VUV" },
  {
    value: "+379",
    country: "Vatican City",
    abbreviation: "VA",
    currency: "EUR",
  },
  { value: "+58", country: "Venezuela", abbreviation: "VE", currency: "VES" },
  { value: "+84", country: "Vietnam", abbreviation: "VN", currency: "VND" },
  {
    value: "+681",
    country: "Wallis and Futuna",
    abbreviation: "WF",
    currency: "XPF",
  },
  { value: "+967", country: "Yemen", abbreviation: "YE", currency: "YER" },
  { value: "+260", country: "Zambia", abbreviation: "ZM", currency: "ZMW" },
  { value: "+263", country: "Zimbabwe", abbreviation: "ZW", currency: "ZWL" },
].sort((a, b) => {
  // Sort based on the first character of the 'country' field
  const firstCharA = a.country[0].toLowerCase(); // Get first character of country (case-insensitive)
  const firstCharB = b.country[0].toLowerCase();
  return firstCharA.localeCompare(firstCharB); // Compare alphabetically
});
export default COUNTRY_CODES;

export const DEFAULT_COUNTRY = COUNTRY_CODES.find(
  (COUNTRY) => COUNTRY.country === "United States",
) as Country;

// Country Schema for Zod Validation
export const countrySchema = z
  .object({
    value: z.string(),
    country: z.string(),
    abbreviation: z.string(),
    currency: z.string(),
  })
  .refine((data) =>
    COUNTRY_CODES.some(
      (c) =>
        c.value === data.value &&
        c.country === data.country &&
        c.abbreviation === data.abbreviation &&
        c.currency === data.currency,
    ),
  );

// Inferred Type of Country Schema
export type TCountry = z.infer<typeof countrySchema>;
